### ISSUE TITLE
Exception for IPV6 address 

### ISSUE THREAD

**Issue by josemonmaliakal** [dpodium/yii2-geoip#1] opened 2015-12-06 05:19 UTC
Hello there , I got an IPv6 address like 2a03:2880:1010:dfe6:face:b00c:0:8000 the extension can't detect the exact location for the same , can we have any solution for that ????
![error](https://cloud.githubusercontent.com/assets/2138435/11611824/fe741566-9c06-11e5-91d5-7beda8a0bf94.png)

**Comment by sionghuat** [comment] 2015-12-07 04:36
Hi, the issue is resolved in version 1.3. Please update and give it a try. Do inform us if the issue persist.

**Comment by sionghuat** [comment] 2015-12-07 05:11
Hi Maliaka,

The issue is fixed in version 1.3.1. Please verify.

Thanks.

On Sun, Dec 6, 2015 at 1:19 PM, Josemon Maliakal <notifications@github.com>
wrote:

> Hello there , I got an IPv6 address like
> 2a03:2880:1010:dfe6:face:b00c:0:8000 the extension can't detect the exact
> location for the same , can we have any solution for that ????
> [image: error]
> <https://cloud.githubusercontent.com/assets/2138435/11611824/fe741566-9c06-11e5-91d5-7beda8a0bf94.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dpodium/yii2-geoip/issues/1>.
>



-- 
<http://www.dpodium.com/>
CH'NG SIONG HUAT
Team Leader,
Technical Development Department,
Dynamic Podium
p:+603 9223 4673 ext 114 <+603%209223%204673%20ext%20110> | m:+6016 795 1012
<+6012%20317%202989>e:sionghuat.chng@dpodium.com |  w:www.dpodium.com
DISCLAIMER: This email and any attachments transmitted with it are intended
solely for the addressee(s), and may contain information that are
privileged and/or confidential. If you are not the intended recipient, or
responsible for delivery of this message to the addressee, please notify
the sender immediately by reply email and delete all copies of the
transmission. The contents of this email may represent the author/sender's
personal opinions, and not necessarily those of Dynamic Podium. As the
email may have been intercepted, corrupted, lost, destroyed, arrive late,
incomplete or contain viruses, no liability is accepted as a result.

**Closed** 2016-07-14 03:58 UTC
